var searchData=
[
  ['handlewidth',['handleWidth',['https://doc.qt.io/qt-5/qsplitter.html#handleWidth-prop',1,'QSplitter']]],
  ['hasblurwindow',['hasBlurWindow',['../class_d_window_manager_helper.html#abdbccafdfd18d951e3d6c5ab1258ee7d',1,'DWindowManagerHelper']]],
  ['hascomposite',['hasComposite',['../class_d_window_manager_helper.html#a1cf88c85cc2befbd1ef8c7ca29ecbfa2',1,'DWindowManagerHelper']]],
  ['hashotspot',['hasHotSpot',['https://doc.qt.io/qt-5/qgesture.html#hasHotSpot-prop',1,'QGesture']]],
  ['hasnotitlebar',['hasNoTitlebar',['../class_d_window_manager_helper.html#aa5b91abd27bd14a6fb067e0a7ab9cd10',1,'DWindowManagerHelper']]],
  ['hasselectedtext',['hasSelectedText',['https://doc.qt.io/qt-5/qlineedit.html#hasSelectedText-prop',1,'QLineEdit::hasSelectedText()'],['https://doc.qt.io/qt-5/qlabel.html#hasSelectedText-prop',1,'QLabel::hasSelectedText()']]],
  ['haswallpapereffect',['hasWallpaperEffect',['../class_d_window_manager_helper.html#a95a707bbbb1640f4ff1047e74ee034c3',1,'DWindowManagerHelper']]],
  ['headerhidden',['headerHidden',['https://doc.qt.io/qt-5/qtreeview.html#headerHidden-prop',1,'QTreeView']]],
  ['height',['height',['https://doc.qt.io/qt-5/qwindow.html#height-prop',1,'QWindow::height()'],['https://doc.qt.io/qt-5/qwidget.html#height-prop',1,'QWidget::height()']]],
  ['highlightsections',['highlightSections',['https://doc.qt.io/qt-5/qheaderview.html#highlightSections-prop',1,'QHeaderView']]],
  ['historytype',['historyType',['https://doc.qt.io/qt-5/qhistorystate.html#historyType-prop',1,'QHistoryState']]],
  ['horizontalcenter',['horizontalCenter',['../class_dtk_1_1_widget_1_1_d_anchors_base.html#a990c6e9474d5cae4ecf80b4f09b9f6d0',1,'Dtk::Widget::DAnchorsBase']]],
  ['horizontalcenteroffset',['horizontalCenterOffset',['../class_dtk_1_1_widget_1_1_d_anchors_base.html#a2b52884009ded8a7812f030d71d3a80b',1,'Dtk::Widget::DAnchorsBase']]],
  ['horizontaldirection',['horizontalDirection',['https://doc.qt.io/qt-5/qswipegesture.html#horizontalDirection-prop',1,'QSwipeGesture']]],
  ['horizontalheaderformat',['horizontalHeaderFormat',['https://doc.qt.io/qt-5/qcalendarwidget.html#horizontalHeaderFormat-prop',1,'QCalendarWidget']]],
  ['horizontalscrollbarpolicy',['horizontalScrollBarPolicy',['https://doc.qt.io/qt-5/qabstractscrollarea.html#horizontalScrollBarPolicy-prop',1,'QAbstractScrollArea']]],
  ['horizontalscrollmode',['horizontalScrollMode',['https://doc.qt.io/qt-5/qabstractitemview.html#horizontalScrollMode-prop',1,'QAbstractItemView']]],
  ['horizontalspacing',['horizontalSpacing',['https://doc.qt.io/qt-5/qgridlayout.html#horizontalSpacing-prop',1,'QGridLayout::horizontalSpacing()'],['https://doc.qt.io/qt-5/qformlayout.html#horizontalSpacing-prop',1,'QFormLayout::horizontalSpacing()'],['../class_dtk_1_1_widget_1_1_d_flow_layout.html#a39940d84fb74402de334b7402175b410',1,'Dtk::Widget::DFlowLayout::horizontalSpacing()']]],
  ['hotspot',['hotSpot',['https://doc.qt.io/qt-5/qgesture.html#hotSpot-prop',1,'QGesture']]],
  ['html',['html',['https://doc.qt.io/qt-5/qtextedit.html#html-prop',1,'QTextEdit']]],
  ['hue',['hue',['../class_dtk_1_1_widget_1_1_d_video_widget.html#a47c2ff0fd7c16d68d5b943651fd48597',1,'Dtk::Widget::DVideoWidget']]]
];
