var searchData=
[
  ['rangeaccessflags',['RangeAccessFlags',['https://doc.qt.io/qt-5/qopenglbuffer.html#RangeAccessFlag-enum',1,'QOpenGLBuffer']]],
  ['readfunc',['ReadFunc',['https://doc.qt.io/qt-5/qsettings.html#ReadFunc-typedef',1,'QSettings']]],
  ['reference',['reference',['https://doc.qt.io/qt-5/qstringview.html#reference-typedef',1,'QStringView::reference()'],['https://doc.qt.io/qt-5/qlatin1string.html#reference-typedef',1,'QLatin1String::reference()'],['https://doc.qt.io/qt-5/qstring.html#reference-typedef',1,'QString::reference()'],['https://doc.qt.io/qt-5/qlist.html#reference-typedef',1,'QList::reference()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reference-typedef',1,'QVarLengthArray::reference()'],['https://doc.qt.io/qt-5/qvector.html#reference-typedef',1,'QVector::reference()'],['https://doc.qt.io/qt-5/qset.html#reference-typedef',1,'QSet::reference()'],['https://doc.qt.io/qt-5/qset-iterator.html#reference-typedef',1,'QSet::iterator::reference()'],['https://doc.qt.io/qt-5/qset-const-iterator.html#reference-typedef',1,'QSet::const_iterator::reference()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#reference-typedef',1,'QFuture::const_iterator::reference()'],['https://doc.qt.io/qt-5/qjsonarray.html#reference-typedef',1,'QJsonArray::reference()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reference-typedef',1,'QLinkedList::reference()']]],
  ['relation',['Relation',['https://doc.qt.io/qt-5/qaccessible.html#RelationFlag-enum',1,'QAccessible']]],
  ['renderflags',['RenderFlags',['https://doc.qt.io/qt-5/qtextitem.html#RenderFlag-enum',1,'QTextItem::RenderFlags()'],['https://doc.qt.io/qt-5/qwidget.html#RenderFlag-enum',1,'QWidget::RenderFlags()']]],
  ['renderhints',['RenderHints',['https://doc.qt.io/qt-5/qpainter.html#RenderHint-enum',1,'QPainter']]],
  ['result',['Result',['https://doc.qt.io/qt-5/qgesturerecognizer.html#ResultFlag-enum',1,'QGestureRecognizer']]],
  ['result_5ftype',['result_type',['https://doc.qt.io/qt-5/qrandomgenerator.html#result_type-typedef',1,'QRandomGenerator::result_type()'],['https://doc.qt.io/qt-5/qrandomgenerator64.html#result_type-typedef',1,'QRandomGenerator64::result_type()']]],
  ['reverse_5fiterator',['reverse_iterator',['https://doc.qt.io/qt-5/qbytearray.html#reverse_iterator-typedef',1,'QByteArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qstringview.html#reverse_iterator-typedef',1,'QStringView::reverse_iterator()'],['https://doc.qt.io/qt-5/qlatin1string.html#reverse_iterator-typedef',1,'QLatin1String::reverse_iterator()'],['https://doc.qt.io/qt-5/qstring.html#reverse_iterator-typedef',1,'QString::reverse_iterator()'],['https://doc.qt.io/qt-5/qlist.html#reverse_iterator-typedef',1,'QList::reverse_iterator()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reverse_iterator-typedef',1,'QVarLengthArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qvector.html#reverse_iterator-typedef',1,'QVector::reverse_iterator()'],['https://doc.qt.io/qt-5/qset.html#reverse_iterator-typedef',1,'QSet::reverse_iterator()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reverse_iterator-typedef',1,'QLinkedList::reverse_iterator()']]]
];
