---
name: BUG Report | 缺陷报告
description: General BUG report
labels: []
assignees: []
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a bug report!**
      **感谢抽出时间汇报 BUG 缺陷！**
      
      A valid bug report should let someone other than you be able to reproduce the same issue, so please provide as much details as possible.
      一个有效的缺陷汇报应当能够使一个你之外的人可以根据所提供的信息有效的复现问题。所以请提供尽可能详细的信息。

      ⚠ Read before creating issue 反馈之前请注意:
      Only report BUG here, please use the [Discussion board][discussion-board] for non-bug feature request, troubleshooting or general discusion.
      非 BUG 的反馈（如特性请求，疑难解答，行为建议，常规讨论）请转到 [Discussion 面板][discussion-board]
      
      [discussion-board]: https://github.com/linuxdeepin/developer-center/discussions/new

- type: textarea
  attributes:
    label: SUMMARY | 问题概要
    description: |
      Describe the bug you want to report
      在这里描述你遇到的 BUG

- type: textarea
  attributes:
    label: DTK and OS VERSIONS | DTK&系统版本信息
    description: |
      Describe your DTK components and system version information here
      在这里描述你的DTK组件和系统版本信息
    placeholder: |
      Example:
      Distribution: deepin v20.9
      Package: dtkcore：5.6.8
  validations:
    required: true

- type: textarea
  attributes:
    label: Minimal Reproducible Case Code | 最小复现案例代码
    description: |
      Here is the code that can reproduce your problem, preferably a project that can run
      这里给出能够复现你的问题的代码，最好是可以运行的项目
  validations:
    required: true

- type: textarea
  attributes:
    label: OBSERVED RESULT | 观察到的结果
    description: |
      describe the observed result
      在这里描述观察到的结果

- type: textarea
  attributes:
    label: EXPECTED RESULT | 期望的结果
    description: |
      describe the expected result
      在这里描述你所期望的结果

- type: textarea
  attributes:
    label: ADDITIONAL INFORMATION | 额外补充
    description: |
      any additional information you may want to provide so we can offer better help
      有什么额外需要补充的信息的话，可以写到这里

...
